[tool.poetry]
name = "ooler-ble-client"
version = "0.1.1"
description = "A library to communicate with Ooler Sleep System Bluetooth devices."
authors = ["Robby Griffin <rgriffin@postlogical.com>"]
license = "Apache-2.0"
readme = "README.md"
packages = [{include = "ooler_ble_client"}]
repository = "https://github.com/PostLogical/ooler_ble_client"

[tool.poetry.dependencies]
python = "^3.9"
bleak = ">=0.19.0"
bleak-retry-connector = ">=2.3.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
